In [1]:
import numpy as np
import pandas as pd

In [2]:
dt=pd.read_csv("healthcare-stroke.csv")

In [3]:
dt.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [4]:
dt.isnull().any()

id                   False
gender               False
age                  False
hypertension         False
heart_disease        False
ever_married         False
work_type            False
Residence_type       False
avg_glucose_level    False
bmi                   True
smoking_status       False
stroke               False
dtype: bool

In [5]:
dt["bmi"].fillna(dt["bmi"].mean(),inplace=True)

In [6]:
dt.isnull().any()

id                   False
gender               False
age                  False
hypertension         False
heart_disease        False
ever_married         False
work_type            False
Residence_type       False
avg_glucose_level    False
bmi                  False
smoking_status       False
stroke               False
dtype: bool

In [7]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
id                   5110 non-null int64
gender               5110 non-null object
age                  5110 non-null float64
hypertension         5110 non-null int64
heart_disease        5110 non-null int64
ever_married         5110 non-null object
work_type            5110 non-null object
Residence_type       5110 non-null object
avg_glucose_level    5110 non-null float64
bmi                  5110 non-null float64
smoking_status       5110 non-null object
stroke               5110 non-null int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.1+ KB


In [8]:
x=dt.iloc[:,1:11].values
y=dt.iloc[:,11:12].values

In [9]:
x

array([['Male', 67.0, 0, ..., 228.69, 36.6, 'formerly smoked'],
       ['Female', 61.0, 0, ..., 202.21, 28.893236911794673,
        'never smoked'],
       ['Male', 80.0, 0, ..., 105.92, 32.5, 'never smoked'],
       ...,
       ['Female', 35.0, 0, ..., 82.99, 30.6, 'never smoked'],
       ['Male', 51.0, 0, ..., 166.29, 25.6, 'formerly smoked'],
       ['Female', 44.0, 0, ..., 85.28, 26.2, 'Unknown']], dtype=object)

In [10]:
y

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [11]:
y.shape

(5110, 1)

In [12]:
x.shape

(5110, 10)

In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[0,4,5,6,9])],remainder="passthrough")
x=ct.fit_transform(x)

In [14]:
x.shape

(5110, 21)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
x_train

array([[1.0, 0.0, 0.0, ..., 0, 67.29, 36.7],
       [1.0, 0.0, 0.0, ..., 0, 83.53, 48.5],
       [0.0, 1.0, 0.0, ..., 0, 65.16, 30.8],
       ...,
       [0.0, 1.0, 0.0, ..., 0, 94.71, 28.4],
       [0.0, 1.0, 0.0, ..., 0, 120.94, 29.7],
       [1.0, 0.0, 0.0, ..., 0, 59.52, 33.2]], dtype=object)

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
ann=Sequential()

In [20]:
ann.add(Dense(10,kernel_initializer="random_uniform",activation="relu"))

In [21]:
ann.add(Dense(20,kernel_initializer="random_uniform",activation="relu"))

In [22]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="sigmoid"))

In [24]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [25]:
ann.fit(x_train,y_train,batch_size=32,epochs=50)

Epoch 1/50
128/128 [==============================] - 1s 1ms/step - loss: 0.6238 - accuracy: 0.9333
Epoch 2/50
128/128 [==============================] - 0s 1ms/step - loss: 0.1978 - accuracy: 0.9501
Epoch 3/50
128/128 [==============================] - 0s 895us/step - loss: 0.1560 - accuracy: 0.9561
Epoch 4/50
128/128 [==============================] - 0s 1ms/step - loss: 0.1622 - accuracy: 0.9501
Epoch 5/50
128/128 [==============================] - 0s 1ms/step - loss: 0.1587 - accuracy: 0.9501
Epoch 6/50
128/128 [==============================] - 0s 848us/step - loss: 0.1365 - accuracy: 0.9578
Epoch 7/50
128/128 [==============================] - 0s 809us/step - loss: 0.1467 - accuracy: 0.9543
Epoch 8/50
128/128 [==============================] - 0s 1ms/step - loss: 0.1531 - accuracy: 0.9508
Epoch 9/50
128/128 [==============================] - 0s 3ms/step - loss: 0.1568 - accuracy: 0.9502
Epoch 10/50
128/128 [==============================] - 0s 3ms/step - loss: 0.1576 - accuracy: 

In [26]:
ypred=ann.predict(x_test)

In [27]:
ypred

array([[5.4682547e-01],
       [7.9127958e-08],
       [4.3697804e-02],
       ...,
       [4.2089224e-03],
       [1.2234333e-01],
       [3.1431317e-03]], dtype=float32)

In [28]:
y_test

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int64)

In [39]:
yp=ann.predict(sc.transform(ct.transform([["Female",29.00,0,0,"Yes","Self-employed","Urban",90.52,28.000000,"never smoked"]])))

In [41]:
yp>0.1

array([[False]])

In [42]:
yp=ann.predict(sc.transform(ct.transform([["Female",79.0,1,0,"Yes","Self-employed","Rural",174.12,24.0,"never smoked"]])))

In [44]:
yp>0.1

array([[ True]])